SCH Retro Additional Field Ingestion
seattleflu/id3c-customizations pull request #283
Opened 2022-02-02 22:39 UTC by truong97

The fields, `admit_during_this_encounter` and `admit_to_icu` from Seattle Children's are added for ingestion. These fields gets parsed and ingested, then stored under `details` -> `responses` in the warehouse.encounter table.

Testing Data Used:
1. SFS_Year1_Main_Data_20210922
2. SFS_Year2_Main_Data_20210923
3. SFS_Year3_Main_Data_20211207

Testing Done Include All 3 Test Data Under Local Production:
1. id3c clinical parse-sch
2. id3c clinical upload
3. id3c etl clinical

Testing went well where the fields showed up as expected. Y1, Y2, and Y3 all have the fields, thus no pre-processing needed.

2022-02-02 22:47 UTC, truong97 commented
![](https://github.trello.services/images/mini-trello-icon.png) [SCH Retrospectives - Additional fields to add for ingestion and investigate Data QC on different IDs](https://trello.com/c/UYYX5XKO/1298-sch-retrospectives-additional-fields-to-add-for-ingestion-and-investigate-data-qc-on-different-ids)

2022-02-07 22:29 UTC, bencap approved these changes
These changes look good to me and all seems to be in order when testing locally, with the fields being ingested into my local database. Still may want a senior dev to sign off on them as well though :)

2022-02-15 18:53 UTC, truong97 commented
For adding new mapping to insurance name, `financial aid` and `self`:

Testing Data Used:

- SFS_Year4_Main_Data_20220124
- SFS_Year4_Main_Data_20220208
- SFS_Year4_Main_Data_20220209

Testing Done Include All 3 Test Data Under Local Production:

- id3c clinical parse-sch
- id3c clinical upload
- id3c etl clinical

Testing went well where the fields, including `admit_during_this_encounter` and `admit_to_icu` showed up as expected. No errors were thrown when new values adding to insurance name mapping.

2022-02-16 22:53 UTC, davereinhart requested changes

2022-02-16 22:53 UTC, davereinhart commented on lib/seattleflu/id3c/cli/command/etl/clinical.py
> +                "AdmitToICU": document.get("admit_to_icu"),
For consistency, these values should probably be converted to "yes/no" using a function (similar to `FluShot`).

2022-02-17 21:48 UTC, truong97 commented
Checks are currently failing b/c https://github.com/seattleflu/id3c/pull/284 needs to be reviewed and approved first.

2022-02-18 21:11 UTC, davereinhart approved these changes
Looks good. 

It might be possible to combine the `admit_encounter` and `admit_icu` mapping functions into a single function, which would work well if these two remain consistent going forward, but keeping them separate will be better in case they diverge.

2022-02-18 22:08 UTC, truong97 commented
The checks were failing, even after deploying https://github.com/seattleflu/id3c/pull/284. I realized that they were because the tests were calling on the wrongly-named functions upon invoking `>>>` inside the comment block (I was calling the parameter instead of the function itself - big oof). There was no actual changes to the code - just changes to the comment block under `admit_encounter()` and `admit_icu()`. This will be corrected before deployment. 

cc @davereinhart, so that you are aware.

2022-02-22 17:27 UTC, davereinhart requested changes

2022-02-22 17:27 UTC, davereinhart commented on lib/seattleflu/id3c/cli/command/etl/clinical.py
> +    id3c.cli.command.etl.UnknownAdmitEncounterResponseError: Unknown admit during this encounter response «maybe»
This string needs to match exactly with that the function is returning below (
"Unknown admit during this encounter response " doesn't match "Unknown admit during encounter response ")

2022-02-22 17:27 UTC, davereinhart commented on lib/seattleflu/id3c/cli/command/etl/clinical.py
> +    id3c.cli.command.etl.UnknownAdmitICUResponseError: Unknown admit to icu response «maybe»
This string also needs to match what is being returned below (case-sensitive).

2022-02-22 19:03 UTC, merged

2022-02-22 19:14 UTC, truong97 commented
Deployed.