Update ETL for SCH Year 4
seattleflu/id3c-customizations pull request #314
Opened 2022-05-18 17:43 UTC by seidelma

2022-05-18 18:41 UTC, davereinhart commented on lib/seattleflu/id3c/cli/command/etl/clinical.py
> +            details["responses"][k] = [document[k]]
Could use the `covid_shot_manufacturer` function here to validate and standardize incoming values.

2022-05-18 18:42 UTC, davereinhart commented on lib/seattleflu/id3c/cli/command/clinical.py
> +        LOG.warning(f"Invalid manufest_format {manifest_format}")
minor typo

2022-05-18 20:16 UTC, davereinhart requested changes
We'll need to add "year4" to the `--manifest-format` option here, and should probably become the new default:
https://github.com/seattleflu/id3c-customizations/blob/seidelma/feature/sch_year_4/lib/seattleflu/id3c/cli/command/clinical.py#L176-L178

2022-05-19 19:11 UTC, davereinhart commented
Picking this work up since @seidelma is out of office.

2022-05-19 19:24 UTC, davereinhart commented
To test, pull the latest SCH Excel file from S3 and run the following three commands:

`envdir ../env.d/deidentification pipenv run id3c clinical parse-sch -o [missing barcodes output file] --manifest-format year4 [path to XLSX file] > [parsed ndjson file]`

`PGSERVICE=seattleflu-local pipenv run id3c clinical upload [parsed ndjson file]`

`PGSERVICE=seattleflu-local LOG_LEVEL=debug pipenv run id3c clinical etl --commit`

2022-05-19 20:15 UTC, kschwabefry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update SCH variables for covid vaccines manufactures](https://trello.com/c/b20Nps57/1368-update-sch-variables-for-covid-vaccines-manufactures)

2022-05-19 20:47 UTC, kschwabefry commented
Looks good for the new data. My main thought here is that its confusing to call the new format year4. The SCH files labeled 'year4' but pre 4/27/22 would actually need to use manifest format 'year3', which seems counterintuitive given the current naming. I think that could be addressed by choosing a format name thats more descriptive than just year, since this was a "mid-year" format change.

2022-05-19 21:15 UTC, davereinhart commented
> Looks good for the new data. My main thought here is that its confusing to call the new format year4. The SCH files labeled 'year4' but pre 4/27/22 would actually need to use manifest format 'year3', which seems counterintuitive given the current naming. I think that could be addressed by choosing a format name thats more descriptive than just year, since this was a "mid-year" format change.

Good point! That would apply to the `year3` value too since it applies to some year4 files, so maybe all of them should be updated to a date range.  (e.g. `20210101-20220426`, `20220427-present`, etc.)

2022-05-19 22:38 UTC, davereinhart commented
Actually, it looks like the new file that was uploaded contains ALL records for year 4, so the previous year 4 files can be archived and the format naming convention can stay intact.

2022-05-19 22:44 UTC, merged

2022-05-19 22:54 UTC, davereinhart commented
Deployed, and moved older format year 4 files to the `archive` subfolder on S3.

2022-05-20 16:16 UTC, kschwabefry commented
Thanks Dave! Good call to archive the previous y4 files if the new 4/27 file includes them.